spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: r1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  batch:
    jdbc:
      initialize-schema: always

